# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicbody', '0017_auto_20180313_0901'),
        ('foirequest', '0017_auto_20180405_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=1000)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('foirequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foirequest.FoiRequest')),
                ('publicbody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.PublicBody')),
            ],
            options={
                'verbose_name': 'Venue Request',
                'verbose_name_plural': 'Venue Requests',
            },
        ),
    ]
