# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 14:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuerequest',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
