# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 14:17
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicbody", "0019_foilaw_law_type"),
        ("foirequest", "0020_auto_20180605_1053"),
        ("froide_food", "0002_auto_20180508_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueRequestItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "foirequest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="foirequest.FoiRequest",
                    ),
                ),
                (
                    "publicbody",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="publicbody.PublicBody",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="froide_food.VenueRequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Request Item",
                "verbose_name_plural": "Venue Requests Items",
            },
        ),
    ]
