# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_food', '0004_auto_20180607_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuerequest',
            name='foirequest',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='publicbody',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='timestamp',
        ),
    ]
