# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_food", "0008_auto_20180710_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuerequest",
            name="last_resolution",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
