# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 16:16
from __future__ import unicode_literals

from django.db import migrations


def add_request_infos(apps, schema_editor):
    VenueRequest = apps.get_model("froide_food", "VenueRequest")
    VenueRequestItem = apps.get_model("froide_food", "VenueRequestItem")

    for vr in VenueRequest.objects.all():
        vris = VenueRequestItem.objects.filter(venue=vr)
        if vris:
            vri = vris[0]
            vr.last_request = vri.foirequest.first_message
            vr.last_status = vri.foirequest.status
            vr.last_resolution = vri.foirequest.resolution
            vr.save()


class Migration(migrations.Migration):

    dependencies = [
        ("froide_food", "0009_venuerequest_last_resolution"),
    ]

    operations = [
        migrations.RunPython(add_request_infos),
    ]
