# Generated by Django 2.1.8 on 2019-06-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_amenities', '0001_initial'),
        ('foirequest', '0039_foirequest_team'),
        ('froide_food', '0011_auto_20190109_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('complaints', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('amenity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_amenities.Amenity')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foirequest.FoiAttachment')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foirequest.FoiMessage')),
            ],
            options={
                'verbose_name': 'food safety report',
                'verbose_name_plural': 'food safety reports',
            },
        ),
        migrations.AddField(
            model_name='venuerequestitem',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyreport',
            name='request_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_food.VenueRequestItem'),
        ),
        migrations.AddField(
            model_name='foodsafetyreport',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_food.VenueRequest'),
        ),
    ]
