# Generated by Django 2.1.11 on 2019-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_food', '0012_auto_20190603_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyreport',
            name='disgusting',
            field=models.BooleanField(default=False),
        ),
    ]
