# Generated by Django 2.2.4 on 2019-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0028_auto_20190527_1410'),
        ('froide_food', '0013_foodsafetyreport_disgusting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAuthorityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publicbodies', models.ManyToManyField(to='publicbody.PublicBody')),
            ],
            options={
                'verbose_name': 'food authority status',
                'verbose_name_plural': 'food authority stati',
            },
        ),
    ]
